server:
  port: 8761

spring:
  application:
    name: discovery-service
  cloud:
    config:
      uri: http://127.0.0.1:8888
      nane: keeping

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false